# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml

# version format
version: "{build}"

configuration:
  - Debug
  - Release

branches:
  only:
    - master

# scripts that run after cloning repository
install:
  - git clone --depth=1 https://github.com/google/googletest.git      third_party/googletest
  - git clone --depth=1 https://github.com/google/re2.git             third_party/re2

build:
  parallel: true  # enable MSBuild parallel builds
  verbosity: minimal

build_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=install -DRE2_BUILD_TESTING=OFF
  - cmake --build . --target install --config %CONFIGURATION%

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure

notifications:
  - provider: Email
    to:
      - dneto@google.com
    subject: 'Effcee Windows Build #{{buildVersion}}: {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
